(defun C:CTLightHole ()
	(vl-load-com)
	(setq oApp (vlax-get-acad-object))
	(vla-RunMacro oApp "SCCommTools.CTLightHole.CTLightHole")
	(princ)
)

(defun C:CTMDGroupObjects ()
	(vl-load-com)
	(setq oApp (vlax-get-acad-object))
	(vla-RunMacro oApp "SCCommTools.CTMDGroupObjects.CTMDGroupObjects")
	(princ)
)

(defun C:CTShowNotLabeledInBOM ()
	(vl-load-com)
	(setq oApp (vlax-get-acad-object))
	(vla-RunMacro oApp "SCCommTools.CTShowNotLabeledInBOM.CTShowNotLabeledInBOM")
	(princ)
)

(defun C:CTImportUCSList ()
	(vl-load-com)
	(setq oApp (vlax-get-acad-object))
	(vla-RunMacro oApp "SCCommTools.CTImportUCSList.CTImportUCSList")
	(princ)
)